name: SmartHive CI — Validate & Manual Deploy

on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  validate:
    name: Validate Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci || true
      - name: Run Validation Script
        run: |
          echo "Running smoke tests..."
          node tests/validateDeployment.js || true
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: validation-report
          path: tests/validationReport.json

  deploy:
    name: Manual Approval Deployment
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Manual Approval Required
        run: echo "Approve this environment to deploy on Vercel."
